### ISSUE TITLE
Autoit >>Mouseclick ,controlclick not working in robot framework ,not able to click any part of screen

### ISSUE THREAD

**Issue by dhingrachirag** [nokia/robotframework-autoitlibrary#12]
Hi 

I just installed auto it library in robot framework and its installed properly and i am able to access all the keywords in framework. The problem what i faced is whenever i am trying to use any click option is not clicking or failing. Somehow i got lucky with mouseclick and its working but problem with this method is its able to point in that particular tab but not clicking.

So after several tries I downloaded official auto it package and i had written the script in scite in .au3 extension. The script worked absolutely fine .Mouseclick is able to point as well as click.

Below are the questions:

Q-I want to know why in robot framework we are not able to get the full functionality of keywords that is there already in auto it if we are able to access auto it keywords in robot framework ?
Q- What 's the workaround for this issue ?

**Comment by lucyking** [comment]
may you help to provide the details about your OS, python, etc software version and the RF auto script?

**Comment by dhingrachirag** [comment]
Hi @lucyking 

PFB the details:

1) OS -Windows 10
2) Python -2.7.14
3) AutoIt Version -v3.3.14.5
3) RF Auto Script -

*** Settings ***
Library  String
Library  Collections
Library  OperatingSystem
Library  AutoItLibrary


*** Variables ***

*** Keywords ***
Signin Accounts in Teams Ciient
  AutoItLibrary.Run  C:\\Users\\NI6350\\AppData\\Local\\Microsoft\\Teams\\Update.exe --processStart "Teams.exe"
  Sleep  15s
  Send  XYZ
  Sleep  10s
  Send  {ENTER}
  Sleep  15s
  Send  ccccc
  Sleep  10s
  Send  {ENTER}
  Sleep  30s


*** Test Cases ***
Able to open ABC or not
  [Documentation]  Able to open ABC
  [Tags]  XXXYYZZ Feature
  Import Library  WhiteLibrary
  Signin Accounts in ZZZZ
  Sleep  10s
  WinActivate  XXXX
  ${out}  WinActive  BBBBB
  Log  ${out}
  AutoItLibrary.MouseClick  "main"  376  32
  Sleep  10s
  MouseDown  "main"
  Sleep  10s
  MouseUp  "main"
  Sleep  10s
  ${out}  WinGetHandle  aaaa
  Log  ${out}
  ${out}  WinGetText  bbbb
  Log  ${out}
  ${out}  WinGetTitle  cccc
  Log  ${out}
  ${out}  ControlGetHandle  "XYZ"  ""  "[CLASS:Intermediate D3D Window; INSTANCE:1]"
  Log  ${out}
  ${out}  ControlSend  "LLLL"  ""  "[CLASS:Intermediate D3D Window; INSTANCE:1]"  MS1
  Log  ${out}
  ${out}  ControlClick  "AAA"  ""  "[CLASS:Intermediate D3D Window; INSTANCE:1]"  "primary"  2  376  32
  Log  ${out}

**Comment by lucyking** [comment]
@dhingrachirag  there, I'll try to reproduce this issue next.

**Comment by dhingrachirag** [comment]
@lucyking - Did u reproduce this isuue ? I am struck and waiting for your response.

**Comment by lucyking** [comment]
@dhingrachirag I met some issue on Windows 10 OS setup.
Can you try using **Python3.7.2** instead of  **Python -2.7.14** then have a try?

**Comment by dhingrachirag** [comment]
@lucyking - My whole setup is build on python 2 as it is the most stable version in robot framework.Many libraries just supports python 2. Will you please let me know in python 2 whats the issue ?

I don't want to change as it's big setup and i don want to change right now to python 3.Thanks in advance!!!

**Comment by lucyking** [comment]
@dhingrachirag  so can you setup TeamViewer then I can remote access your PC for debug.
(There's no issue with py2 at present, I just wonder if it's too older.Official will NOT provide support for py2 sooner).

**Comment by dhingrachirag** [comment]
@lucyking -Sure .Will you let me know the time so that I will share my screen to you ?

**Comment by lucyking** [comment]
how about 20:30 today?

2019年2月11日 18:04，"dhingrachirag" <notifications@github.com>写道：

**Comment by dhingrachirag** [comment]
@lucyking - If You don't mind .Shall we schedule at 19:00  ?

Regards

**Comment by dhingrachirag** [comment]
@lucyking - PF my invite.

Hello,

Please join the meeting, by clicking on this link:
https://go.teamviewer.com/v14/m42716608

Meeting ID: m42-716-608


Regards,
Chirag Dhingra


www.teamviewer.com - Easy online meeting & screen sharing

**Comment by lucyking** [comment]
ok, I walk to home now. may online 15mins later.

2019年2月11日 18:54，"dhingrachirag" <notifications@github.com>写道：

@lucyking <https://github.com/lucyking> - PF my invite.

Hello,

Please join the meeting, by clicking on this link:
https://go.teamviewer.com/v14/m42716608

Meeting ID: m42-716-608

Regards,
Chirag Dhingra

www.teamviewer.com - Easy online meeting & screen sharing

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lucyking/robotframework-autoitlibrary/issues/12#issuecomment-462287125>,
or mute the thread

**Comment by dhingrachirag** [comment]
@lucyking -Just ping me when you are there.

**Comment by lucyking** [comment]
@dhingrachirag 
- The reason is you giving invalid args. You should use as blow:
```
AutoItLibrary.MouseClick   \    376    32    1    300
```


- You can use [robotframework-RIDE](https://github.com/robotframework/RIDE) editor  to keep the input valid, and refer to fx() usage easily by Ctrl+M:
![fx](https://raw.githubusercontent.com/lucyking/Instroduction/master/issue/robotframework-autoitlibrary/12/fx.gif)

- I found the **Microfost Desktop App - Teams.exe** is an embedd Web application. It's hard to auto test it with AutoIt, unless you hard coding (X, Y)  coordinate as you do in the pure AutoIt script, which is poor of robustness.
![1](https://raw.githubusercontent.com/lucyking/Instroduction/master/issue/robotframework-autoitlibrary/12/1.PNG)
- Suggest you use [robotframework-Selenium2Library](https://github.com/robotframework/Selenium2Library) to interact with the [Web version](https://teams.microsoft.com) of **Microsoft Teams** and locate the element/button directly by web elements' id/name/xpath:
![howto](https://raw.githubusercontent.com/lucyking/Instroduction/master/issue/robotframework-autoitlibrary/12/HowToSelenium2.gif)

**Comment by dhingrachirag** [comment]
@lucyking 

I want to understand some things as below:
1) So automation through auto it library is not possible in robot framework in this case. If its not possible then which library we should use particularly to automate window application if that is the case ?

2) If we don't have option to interact with web version in this case then what's the way out ?

Thanks in advance!!!

**Comment by lucyking** [comment]
@dhingrachirag We ever met the same scene that Android App has WebView embedded. Then we use  robotframework-aircvlibrary, which get element (X,Y) by picture compare , to locate element.
Its advantage is you needn't consider what's the targat application's constitution. As soon as you can take screenshot and provide the reference picture of target element, you can locate it.
Its shortcome is that you need provide lots of reference pics.
